name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Add Capacitor Android
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android --save
          npx cap add android || echo "Android already exists"

      - name: Prepare Gradle Wrapper
        run: |
          mkdir -p android/gradle/wrapper
          curl -L https://services.gradle.org/distributions/gradle-8.2.1-bin.zip -o gradle-8.2.1-bin.zip
          unzip -q gradle-8.2.1-bin.zip -d gradle-8.2.1
          cd android
          ../gradle-8.2.1/gradle-8.2.1/bin/gradle wrapper --gradle-version 8.2.1
          chmod +x gradlew

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
