name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Install Capacitor
        run: |
          npm install @capacitor/core @capacitor/cli --save
          npx cap init fintrack com.fintrack.app --web-dir=dist
          npx cap add android

      - name: Copy build to Android
        run: npx cap copy android

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: cd android && ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: FinTrack-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

